// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmwom6OskXzoygc6LbhHyh5S9fdPScnQw',
    appId: '1:89762568465:web:31e23585940002104814b0',
    messagingSenderId: '89762568465',
    projectId: 'copainquizapp',
    authDomain: 'copainquizapp.firebaseapp.com',
    storageBucket: 'copainquizapp.appspot.com',
    measurementId: 'G-V0Z8507E3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOHlok1saX--USoUsjP6rXtOkZcsOZ6xk',
    appId: '1:89762568465:android:8c17a2dc23d1cfe04814b0',
    messagingSenderId: '89762568465',
    projectId: 'copainquizapp',
    storageBucket: 'copainquizapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT60XvztMvvwQ-oZ88mmSK8WA3lJNt91g',
    appId: '1:89762568465:ios:1ebbce138edfd5e74814b0',
    messagingSenderId: '89762568465',
    projectId: 'copainquizapp',
    storageBucket: 'copainquizapp.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT60XvztMvvwQ-oZ88mmSK8WA3lJNt91g',
    appId: '1:89762568465:ios:d6779fb6f4dfcc484814b0',
    messagingSenderId: '89762568465',
    projectId: 'copainquizapp',
    storageBucket: 'copainquizapp.appspot.com',
    iosBundleId: 'com.example.quizApp.RunnerTests',
  );
}
